=== MixJade/PythonLearn/ownWork/utils/xsds/btnRole.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    <!-- 根元素menuList -->
    <xsd:element name="menuList">
        <xsd:complexType>
            <xsd:sequence>
                <!-- 包含一个或多个menu元素 -->
                <xsd:element name="menu" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <!-- 包含一个或多个btn元素 -->
                            <xsd:element name="btn" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <!-- 包含一个或多个role元素 -->
                                    <xsd:sequence>
                                        <xsd:element name="role" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <!-- role元素的属性 -->
                                                <xsd:attribute name="roleNo" type="xsd:string" use="required"/>
                                                <xsd:attribute name="roleName" type="xsd:string" use="required"/>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                    <!-- btn元素的属性 -->
                                    <xsd:attribute name="btnName" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <!-- menu元素的属性 -->
                        <xsd:attribute name="menuNo" type="xsd:string" use="required"/>
                        <xsd:attribute name="desc" type="xsd:string" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== MixJade/PythonLearn/ownWork/xml生成按钮sql/按钮及权限.xml
<menuList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../utils/xsds/btnRole.xsd">
    <!-- 设定按钮所属菜单-->
    <menu menuNo="A0123" desc="试做雷神">
        <!-- 设定按钮名称-->
        <btn btnName="便宜按钮">
            <!-- 设定拥有按钮的角色-->
            <role roleNo="SH007" roleName="高级特工"/>
            <role roleNo="SH008" roleName="便宜特工"/>
        </btn>
        <!-- 可以有多个按钮-->
        <btn btnName="高级按钮">
            <role roleNo="SH007" roleName="高级特工"/>
        </btn>
    </menu>
    <!-- 设定按钮所属菜单-->
    <menu menuNo="A0121" desc="试用古华">
        <btn btnName="古华按钮">
            <role roleNo="SH008" roleName="便宜特工"/>
        </btn>
    </menu>
</menuList>
