=== MixJade/PythonLearn/ownWork/utils/xsds/fieldSQL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    <xsd:element name="tableList">
        <xsd:complexType>
            <xsd:sequence>
                <!-- 包含一个或多个table元素 -->
                <xsd:element name="table" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <!-- 包含一个或多个field元素 -->
                            <xsd:element name="field" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:attribute name="code" type="xsd:string" use="required"/>
                                    <xsd:attribute name="name" type="xsd:string" use="required"/>
                                    <xsd:attribute name="length" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <!-- table元素的属性 -->
                        <xsd:attribute name="code" type="xsd:string" use="required"/>
                        <xsd:attribute name="name" type="xsd:string" use="required"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== MixJade/PythonLearn/ownWork/xml参照旧表字段/待新增的字段.xml
<?xml version='1.0' encoding='UTF-8'?>
<tableList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../ownWork/utils/xsds/fieldSQL.xsd">
  <table code="STUDENT_INF" name="学生表">
    <field code="APPLY_CONDITION" name="申请条件" length=""/>
    <field code="OTHER_CONDITION" name="其他附加申请条件" length=""/>
    <field code="B_LIVE_END_YEAR" name="自定义终止年份" length=""/>
    <field code="B_LIVE_START_YEAR" name="自定义起始年份" length=""/>
    <field code="B_LIVE_TIME_FLG" name="分配起始时间标识" length=""/>
    <field code="LIVE_AMT" name="固定分配金额" length=""/>
    <field code="LIVE_FREQ" name="分配频率" length=""/>
    <field code="LIVE_START" name="分配起始时间" length=""/>
    <field code="LIVE_START_CONDITION" name="分配起始条件" length=""/>
  </table>
</tableList>
